AWSTemplateFormatVersion: '2010-09-09'
Resources:
  JSCTrackerApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: JSC-Tracker

  JSCTrackerUserResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt JSCTrackerApi.RootResourceId
      PathPart: user
      RestApiId: !Ref JSCTrackerApi

  JSCTrackerUserIdResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref JSCTrackerUserResource
      PathPart: "{user_id}"
      RestApiId: !Ref JSCTrackerApi

  GetUserInfoMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref JSCTrackerApi
      ResourceId: !Ref JSCTrackerUserIdResource
      HttpMethod: GET
      AuthorizationType: NONE
      RequestParameters:
        method.request.path.user_id: true
        method.request.querystring.brief: false
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub
          - "arn:aws:apigateway:us-west-2:lambda:path/2015-03-31/functions/${LambdaFunctionArn}/invocations"
          - LambdaFunctionArn: !ImportValue jsc-tracker-lambda-JSCTrackerGetUserInfoLambdaFunctionArn

  # JSCTrackerContactsResource:
  #   Type: AWS::ApiGateway::Resource
  #   Properties:
  #     ParentId: !Ref JSCTrackerUserIdResource
  #     PathPart: contacts
  #     RestApiId: !Ref JSCTrackerApi

  # AddContactMethod:
  #   Type: AWS::ApiGateway::Method
  #   Properties:
  #     RestApiId: !Ref JSCTrackerApi
  #     ResourceId: !Ref JSCTrackerContactsResource
  #     HttpMethod: POST
  #     AuthorizationType: NONE
  #     RequestParameters:
  #       method.request.path.user_id: true
  #     Integration:
  #       Type: AWS_PROXY
  #       IntegrationHttpMethod: POST
  #       Uri: !Sub "arn:aws:apigateway:us-west-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-west-2:373705399158:function:JSCTrackerAddContact/invocations"

  # JSCTrackerContactResource:
  #   Type: AWS::ApiGateway::Resource
  #   Properties:
  #     ParentId: !Ref JSCTrackerUserIdResource
  #     PathPart: contact
  #     RestApiId: !Ref JSCTrackerApi

  # JSCTrackerContactIdResource:
  #   Type: AWS::ApiGateway::Resource
  #   Properties:
  #     ParentId: !Ref JSCTrackerContactResource
  #     PathPart: "{contact_id}"
  #     RestApiId: !Ref JSCTrackerApi

  # UpdateContactMethod:
  #   Type: AWS::ApiGateway::Method
  #   Properties:
  #     RestApiId: !Ref JSCTrackerApi
  #     ResourceId: !Ref JSCTrackerContactIdResource
  #     HttpMethod: PATCH
  #     AuthorizationType: NONE
  #     RequestParameters:
  #       method.request.path.user_id: true
  #       method.request.path.contact_id: true
  #     Integration:
  #       Type: AWS_PROXY
  #       IntegrationHttpMethod: POST
  #       Uri: !Sub "arn:aws:apigateway:us-west-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-west-2:373705399158:function:JSCTrackerUpdateContact/invocations"

  # DeactivateContactResource:
  #   Type: AWS::ApiGateway::Resource
  #   Properties:
  #     ParentId: !Ref JSCTrackerContactIdResource
  #     PathPart: deactivate
  #     RestApiId: !Ref JSCTrackerApi

  # DeactivateContactMethod:
  #   Type: AWS::ApiGateway::Method
  #   Properties:
  #     RestApiId: !Ref JSCTrackerApi
  #     ResourceId: !Ref DeactivateContactResource
  #     HttpMethod: PUT
  #     AuthorizationType: NONE
  #     RequestParameters:
  #       method.request.path.user_id: true
  #       method.request.path.contact_id: true
  #     Integration:
  #       Type: AWS_PROXY
  #       IntegrationHttpMethod: POST
  #       Uri: !Sub "arn:aws:apigateway:us-west-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-west-2:373705399158:function:JSCTrackerDeactivateContact/invocations"

  JSCTrackerDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref JSCTrackerApi
      StageName: prod
    DependsOn:
      - GetUserInfoMethod
      # - AddContactMethod
      # - UpdateContactMethod
      # - DeactivateContactMethod

  LambdaPermissionGetUserInfo:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        !ImportValue 'jsc-tracker-lambda-JSCTrackerGetUserInfoLambdaFunctionArn'
      Principal: apigateway.amazonaws.com

  # LambdaPermissionAddContact:
  #   Type: AWS::Lambda::Permission
  #   Properties:
  #     Action: lambda:InvokeFunction
  #     FunctionName: arn:aws:lambda:us-west-2:373705399158:function:JSCTrackerAddContact
  #     Principal: apigateway.amazonaws.com

  # LambdaPermissionUpdateContact:
  #   Type: AWS::Lambda::Permission
  #   Properties:
  #     Action: lambda:InvokeFunction
  #     FunctionName: arn:aws:lambda:us-west-2:373705399158:function:JSCTrackerUpdateContact
  #     Principal: apigateway.amazonaws.com

  # LambdaPermissionDeactivateContact:
  #   Type: AWS::Lambda::Permission
  #   Properties:
  #     Action: lambda:InvokeFunction
  #     FunctionName: arn:aws:lambda:us-west-2:373705399158:function:JSCTrackerDeactivateContact
  #     Principal: apigateway.amazonaws.com

Outputs:
  JSCTrackerApiId:
    Description: ID of the REST API
    Value: !Ref JSCTrackerApi
    Export:
      Name: !Sub '${AWS::StackName}-JSCTrackerApiId'
  JSCTrackerApiRootResourceId:
    Description: Root resource ID of the API
    Value: !GetAtt JSCTrackerApi.RootResourceId
    Export:
      Name: !Sub '${AWS::StackName}-JSCTrackerApiRootResourceId'
  JSCTrackerGetUserInfoMethodId:
    Description: ID of the GetUserInfo method
    Value: !Ref GetUserInfoMethod
    Export:
      Name: !Sub '${AWS::StackName}-JSCTrackerGetUserInfoMethodId'
