AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for JSCTracker Lambda functions'

Resources:
  JSCTrackerSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      # At the moment this is the only secret we need
      Description: 'Salt for email SHA1'
      GenerateSecretString:
        SecretStringTemplate: '{}'
        GenerateStringKey: 'email_sha1_salt'
        ExcludeLowercase: false
        ExcludeNumbers: false
        ExcludePunctuation: true
        ExcludeUppercase: false
        IncludeSpace: false
        PasswordLength: 8
        RequireEachIncludedType: false
      Name: 'jsc-tracker-email-sha1-salt'

  JSCTrackerLambdaSecretPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: 'JSC-Tracker-Lambda-Secret-Access'
      Roles:
        - Fn::ImportValue: 'jsc-tracker-dynamodb-JSCTrackerDynamoDBRoleName'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: secretsmanager:GetSecretValue
            Resource: !Ref JSCTrackerSecret

  JSCTrackerGetUserUserIdLambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: 'JSCTrackerGetUserUserId'
      Handler: 'get_user_user_id.lambda_handler'
      Role:
        !ImportValue 'jsc-tracker-dynamodb-JSCTrackerDynamoDBRoleArn'
      Code:
        S3Bucket: 'static.us-west-2.infinitequack.net'
        S3Key: 'lambda/jsc-tracker-lambda.zip'
      Runtime: ruby3.3
      Timeout: 30
      MemorySize: 128

  JSCTrackerPostUserUserIdLambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: 'JSCTrackerPostUserUserId'
      Handler: 'post_user_user_id.lambda_handler'
      Role:
        !ImportValue 'jsc-tracker-dynamodb-JSCTrackerDynamoDBRoleArn'
      Code:
        S3Bucket: 'static.us-west-2.infinitequack.net'
        S3Key: 'lambda/jsc-tracker-lambda.zip'
      Runtime: ruby3.3
      Timeout: 30
      MemorySize: 128

  JSCTrackerPostUserUserIdContactNewLambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: 'JSCTrackerPostUserUserIdContactNew'
      Handler: 'post_user_user_id_contact_new.lambda_handler'
      Role:
        !ImportValue 'jsc-tracker-dynamodb-JSCTrackerDynamoDBRoleArn'
      Code:
        S3Bucket: 'static.us-west-2.infinitequack.net'
        S3Key: 'lambda/jsc-tracker-lambda.zip'
      Runtime: ruby3.3
      Timeout: 30
      MemorySize: 128

  JSCTrackerPostUserUserIdContactContactIdLambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: 'JSCTrackerPostUserUserIdContactContactId'
      Handler: 'post_user_user_id_contact_contact_id.lambda_handler'
      Role:
        !ImportValue 'jsc-tracker-dynamodb-JSCTrackerDynamoDBRoleArn'
      Code:
        S3Bucket: 'static.us-west-2.infinitequack.net'
        S3Key: 'lambda/jsc-tracker-lambda.zip'
      Runtime: ruby3.3
      Timeout: 30
      MemorySize: 128

  JSCTrackerPostAdminJscNewLambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: 'JSCTrackerPostAdminJscNew'
      Handler: 'post_admin_jsc_new.lambda_handler'
      Role:
        !ImportValue 'jsc-tracker-dynamodb-JSCTrackerDynamoDBRoleArn'
      Code:
        S3Bucket: 'static.us-west-2.infinitequack.net'
        S3Key: 'lambda/jsc-tracker-lambda.zip'
      Runtime: ruby3.3
      Timeout: 30
      MemorySize: 128

Outputs:
  JSCTrackerGetUserUserIdLambdaFunctionArn:
    Description: 'ARN of the GetUserUserId Lambda function'
    Value: !GetAtt JSCTrackerGetUserUserIdLambdaFunction.Arn
    Export:
      Name: !Sub '${AWS::StackName}-JSCTrackerGetUserUserIdLambdaFunctionArn'
  JSCTrackerPostUserUserIdLambdaFunctionArn:
    Description: 'ARN of the PostUserUserId Lambda function'
    Value: !GetAtt JSCTrackerPostUserUserIdLambdaFunction.Arn
    Export:
      Name: !Sub '${AWS::StackName}-JSCTrackerPostUserUserIdLambdaFunctionArn'
  JSCTrackerPostUserUserIdContactNewLambdaFunctionArn:
    Description: 'ARN of the PostUserUserIdContactNew Lambda function'
    Value: !GetAtt JSCTrackerPostUserUserIdContactNewLambdaFunction.Arn
    Export:
      Name: !Sub '${AWS::StackName}-JSCTrackerPostUserUserIdContactNewLambdaFunctionArn'
  JSCTrackerPostUserUserIdContactContactIdLambdaFunctionArn:
    Description: 'ARN of the PostUserUserIdContactContactId Lambda function'
    Value: !GetAtt JSCTrackerPostUserUserIdContactContactIdLambdaFunction.Arn
    Export:
      Name: !Sub '${AWS::StackName}-JSCTrackerPostUserUserIdContactContactIdLambdaFunctionArn'
  JSCTrackerPostAdminJscNewLambdaFunctionArn:
    Description: 'ARN of the PostAdminJscNew Lambda function'
    Value: !GetAtt JSCTrackerPostAdminJscNewLambdaFunction.Arn
    Export:
      Name: !Sub '${AWS::StackName}-JSCTrackerPostAdminJscNewLambdaFunctionArn'
