AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  JSCTrackerDomainName:
    Type: String
    Default: "jsc-tracker.infinitequack.net"
    Description: The domain name for the API Gateway.
  HostedZoneId:
    Type: String
    Default: "Z04354022LVBEOB5Q6PK4"
    Description: The zone ID in Route53.

Resources:
  JSCTrackerApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: JSC-Tracker
      Description: API Gateway for JSC Tracker
      EndpointConfiguration:
        Types:
          - REGIONAL
      # This appears to be necessary in order to create the alias 'A' record
      DisableExecuteApiEndpoint: false

  JSCTrackerCustomDomainName:
    Type: AWS::ApiGateway::DomainName
    Properties:
      RegionalCertificateArn: !ImportValue 'domain-certificate-DomainCertificateArn'
      DomainName: !Ref JSCTrackerDomainName
      EndpointConfiguration:
        Types:
          - REGIONAL

  JSCTrackerDNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref JSCTrackerDomainName
      Type: A
      AliasTarget:
         DNSName: !GetAtt
          - JSCTrackerCustomDomainName
          - RegionalDomainName
         # https://docs.aws.amazon.com/general/latest/gr/apigateway.html
         HostedZoneId: Z2OJLYMUO9EFXC

  JSCTrackerBasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      BasePath: ''
      DomainName: !Ref JSCTrackerDomainName
      RestApiId: !Ref JSCTrackerApi
      Stage: 'prod'

  # /user
  JSCTrackerUserResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt JSCTrackerApi.RootResourceId
      PathPart: user
      RestApiId: !Ref JSCTrackerApi

  # /user/{user_id}
  JSCTrackerUserUserIdResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref JSCTrackerUserResource
      PathPart: "{user_id}"
      RestApiId: !Ref JSCTrackerApi

  # GET /user/{user_id}
  JSCTrackerGetUserUserIdMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref JSCTrackerApi
      ResourceId: !Ref JSCTrackerUserUserIdResource
      HttpMethod: GET
      AuthorizationType: NONE
      RequestParameters:
        method.request.path.user_id: true
        method.request.querystring.brief: false
      Integration:
        Type: AWS_PROXY
        # This must be POST, per https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apigateway-method-integration.html
        IntegrationHttpMethod: POST
        Uri: !Sub
          - "arn:aws:apigateway:us-west-2:lambda:path/2015-03-31/functions/${LambdaFunctionArn}/invocations"
          - LambdaFunctionArn: !ImportValue jsc-tracker-lambda-JSCTrackerGetUserUserIdLambdaFunctionArn

  # OPTIONS /user/{user_id}
  JSCTrackerOptionsUserUserIdMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref JSCTrackerApi
      ResourceId: !Ref JSCTrackerUserUserIdResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Origin: "'https://static.infinitequack.net,http://localhost:3000'"
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"
              method.response.header.Access-Control-Max-Age: "'600'"
            ResponseTemplates:
              application/json: ''
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: true
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Max-Age: true
          ResponseModels:
            application/json: Empty

  # POST /user/{user_id}
  JSCTrackerPostUserUserIdMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref JSCTrackerApi
      ResourceId: !Ref JSCTrackerUserUserIdResource
      HttpMethod: POST
      AuthorizationType: NONE
      RequestParameters:
        method.request.path.user_id: true
        method.request.querystring.brief: false
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub
          - "arn:aws:apigateway:us-west-2:lambda:path/2015-03-31/functions/${LambdaFunctionArn}/invocations"
          - LambdaFunctionArn: !ImportValue jsc-tracker-lambda-JSCTrackerPostUserUserIdLambdaFunctionArn

  # OPTIONS /user
  JSCTrackerOptionsUserMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref JSCTrackerApi
      ResourceId: !Ref JSCTrackerUserResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Origin: "'https://static.infinitequack.net,http://localhost:3000'"
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"
              method.response.header.Access-Control-Max-Age: "'600'"
            ResponseTemplates:
              application/json: ''
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: true
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Max-Age: true
          ResponseModels:
            application/json: Empty

  JSCTrackerDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref JSCTrackerApi
      StageName: prod
    DependsOn:
      - JSCTrackerGetUserUserIdMethod
      - JSCTrackerPostUserUserIdMethod

  JSCTrackerLambdaPermissionGetUserUserId:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        !ImportValue 'jsc-tracker-lambda-JSCTrackerGetUserUserIdLambdaFunctionArn'
      Principal: apigateway.amazonaws.com

  JSCTrackerLambdaPermissionPostUserUserId:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        !ImportValue 'jsc-tracker-lambda-JSCTrackerPostUserUserIdLambdaFunctionArn'
      Principal: apigateway.amazonaws.com

Outputs:
  JSCTrackerApiId:
    Description: ID of the REST API
    Value: !Ref JSCTrackerApi
    Export:
      Name: !Sub '${AWS::StackName}-JSCTrackerApiId'

  JSCTrackerRegionalDomainName:
    Description: Regional domain name of the API
    Value: !GetAtt
      - JSCTrackerCustomDomainName
      - RegionalDomainName
    Export:
      Name: !Sub '${AWS::StackName}-JSCTrackerRegionalDomainName'

  JSCTrackerApiRootResourceId:
    Description: Root resource ID of the API
    Value: !GetAtt JSCTrackerApi.RootResourceId
    Export:
      Name: !Sub '${AWS::StackName}-JSCTrackerApiRootResourceId'

  JSCTrackerGetUserUserIdMethodId:
    Description: ID of the GetUserUserId method
    Value: !Ref JSCTrackerGetUserUserIdMethod
    Export:
      Name: !Sub '${AWS::StackName}-JSCTrackerGetUserUserIdMethodId'
